# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Golden schema compilation and management utilities for Cloud Spanner migrations."""

from pathlib import Path
from unittest.mock import MagicMock

from datacommons_db.clients import ExecutionStatus, SpannerClient
from datacommons_db.migrations.migration_runner import MigrationRunner
from datacommons_db.utils.sql_utils import (
    get_schema_dir,
    parse_sql_to_statements,
    render_schema_template,
)

GOLDEN_SCHEMA_HEADER = """-- Copyright 2026 Google LLC.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- ============================================================================
-- ⛔ AUTOGENERATED FILE - DO NOT EDIT DIRECTLY!
-- ============================================================================
-- This golden schema represents the cumulative Cloud Spanner schema generated
-- by applying schema.sql followed by all forward migration scripts up to HEAD.
--
-- To update this file when adding or editing migrations:
--   uv run datacommons-devtools migrations update-golden
-- ============================================================================
"""


def get_golden_schema_path() -> Path:
    """Resolves the path to the golden schema SQL file.

    Returns:
        Path to packages/datacommons-db/tests/goldens/schema_golden.sql.
    """
    pkg_root = Path(__file__).resolve().parent.parent.parent
    return pkg_root / "tests" / "goldens" / "schema_golden.sql"


def generate_golden_schema_sql(project_id: str = "test-project") -> str:
    """Generates the cumulative golden schema SQL string from baseline schema.sql and all migrations.

    Args:
        project_id: GCP project ID used for model endpoint interpolation.

    Returns:
        Formatted golden schema SQL string with license header.
    """
    schema_dir = get_schema_dir()
    schema_sql_path = schema_dir / "schema.sql"
    template_content = schema_sql_path.read_text(encoding="utf-8")

    rendered = render_schema_template(template_content, project_id=project_id)
    baseline_statements = parse_sql_to_statements(rendered)

    # Collect DDL statements from all forward migration scripts
    mock_client = MagicMock(spec=SpannerClient)
    mock_client.table_exists.return_value = False
    mig_statements: list[str] = []
    mock_client.execute_ddl.side_effect = lambda stmts: (
        mig_statements.extend(stmts),
        MagicMock(status=ExecutionStatus.SUCCESS),
    )[1]

    runner = MigrationRunner(mock_client)
    for migration in runner.migrations:
        migration.upgrade(mock_client)

    all_stmts = baseline_statements + [s.strip() for s in mig_statements if s.strip()]
    return GOLDEN_SCHEMA_HEADER + "\n" + ";\n\n".join(all_stmts) + ";\n"
