# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Schema snapshot compilation and management utilities for Cloud Spanner migrations."""

from collections.abc import Callable, Sequence
from pathlib import Path
from unittest.mock import MagicMock

from datacommons_db.clients import ExecutionStatus, SpannerClient
from datacommons_db.migrations.emulator import (
    ephemeral_emulator_database,
)
from datacommons_db.migrations.migration_runner import MigrationRunner

SCHEMA_SNAPSHOT_HEADER = """-- ============================================================================
-- ⛔ AUTOGENERATED FILE - DO NOT EDIT DIRECTLY!
-- ============================================================================
-- This snapshot represents the engine-collapsed Cloud Spanner schema generated
-- by executing baseline_schema.sql and all migrations against Cloud Spanner / emulator.
--
-- To update this file when adding or editing migrations:
--   uv run datacommons-devtools migrations update-snapshot
-- ============================================================================
"""

EMULATOR_SKIPPED_BANNER = """

-- ============================================================================
-- ⏭️ Schema Objects Skipped on Spanner Emulator
-- ============================================================================
-- The following DDL statements are defined in migrations flagged with
-- emulator_supported = False (e.g. remote Vertex AI Model registrations that
-- require live Cloud Spanner and Vertex AI infrastructure).
-- ============================================================================
"""


def get_schema_snapshot_path() -> Path:
    """Resolves the path to the cumulative schema snapshot SQL file.

    Returns:
        Path to packages/datacommons-db/tests/snapshots/schema_snapshot.sql.
    """
    pkg_root = Path(__file__).resolve().parent.parent.parent
    return pkg_root / "tests" / "snapshots" / "schema_snapshot.sql"


def _collect_skipped_migration_statements(
    runner: MigrationRunner,
    project_id: str,
    region: str,
    progress_callback: Callable[[str], None] | None = None,
) -> list[str]:
    """Collects DDL statements from migrations not supported by the local emulator."""
    mock_client = MagicMock(spec=SpannerClient)
    mock_client.table_exists.return_value = False
    mock_client.project_id = project_id
    mock_client.region = region
    mock_client.is_emulator = False

    skipped_statements: list[str] = []
    mock_client.execute_ddl.side_effect = lambda stmts: (
        skipped_statements.extend(stmts),
        MagicMock(status=ExecutionStatus.SUCCESS),
    )[1]

    for migration in runner.migrations:
        if not migration.emulator_supported:
            migration.upgrade(mock_client)
            if progress_callback:
                progress_callback(
                    f"  ✔ Appended emulator-skipped statement ({migration.description})"
                )

    return [s.strip() for s in skipped_statements if s.strip()]


def _format_snapshot_sql(
    engine_statements: Sequence[str],
    skipped_statements: Sequence[str] | None = None,
) -> str:
    """Combines engine statements and emulator-skipped statements into SQL text."""
    engine_sql = ";\n\n".join(s.strip() for s in engine_statements if s.strip()) + ";"
    if skipped_statements:
        skipped_sql = (
            ";\n\n".join(s.strip() for s in skipped_statements if s.strip()) + ";\n"
        )
        return f"{SCHEMA_SNAPSHOT_HEADER}\n{engine_sql}{EMULATOR_SKIPPED_BANNER}\n{skipped_sql}"
    return f"{SCHEMA_SNAPSHOT_HEADER}\n{engine_sql}\n"


def generate_engine_schema_snapshot_sql(
    project_id: str = "default",
    region: str = "us-central1",
    emulator_host: str | None = None,
    progress_callback: Callable[[str], None] | None = None,
) -> str:
    """Generates the true engine-collapsed schema snapshot using the Spanner emulator.

    Deploys baseline_schema.sql and all forward migrations to an ephemeral in-memory
    database on the emulator, extracts the materialized DDL from database_admin_api,
    and appends emulator-skipped statements (e.g. remote Vertex AI models).

    Args:
        project_id: GCP project identifier. Defaults to 'default'.
        region: GCP region for model endpoints. Defaults to 'us-central1'.
        emulator_host: Optional emulator address. If None, auto-discovers or starts emulator.
        progress_callback: Optional callback for reporting real-time progress messages.

    Returns:
        Canonical engine-collapsed schema snapshot SQL string.

    Raises:
        ConnectionError: If the Spanner emulator is not reachable and auto-start fails.
        RuntimeError: If database initialization or migration execution fails.
    """
    with ephemeral_emulator_database(
        project_id=project_id,
        region=region,
        emulator_host=emulator_host,
        progress_callback=progress_callback,
    ) as (client, db, spanner_client):
        if progress_callback:
            progress_callback("📜 Applying baseline schema (baseline_schema.sql)...")
        init_res = spanner_client.initialize_database()
        if init_res.status != ExecutionStatus.SUCCESS:
            raise RuntimeError(
                f"Failed to initialize baseline schema on emulator: {init_res.error_message}"
            )

        runner = MigrationRunner(spanner_client)
        pending = runner.get_pending_migrations()
        if progress_callback:
            progress_callback(
                f"⚡ Applying {len(pending)} forward schema migration(s)..."
            )

        for migration in pending:
            runner.apply_migration(migration)
            if progress_callback:
                progress_callback(
                    f"  ✔ Applied {migration.creation_timestamp}: {migration.description}"
                )

        if progress_callback:
            progress_callback(
                "🔬 Introspecting engine-materialized DDL from Spanner..."
            )
        response = client.database_admin_api.get_database_ddl(database=db.name)
        engine_statements = list(response.statements)
        if progress_callback:
            progress_callback(
                f"  ✔ Extracted {len(engine_statements)} collapsed schema statements"
            )

        skipped = _collect_skipped_migration_statements(
            runner, project_id, region, progress_callback
        )
        return _format_snapshot_sql(engine_statements, skipped)


def write_compiled_schema(
    target_path: Path | None = None,
    project_id: str = "default",
    region: str = "us-central1",
    *,
    progress_callback: Callable[[str], None] | None = None,
) -> Path:
    """Compiles and writes the cumulative schema snapshot using the Spanner emulator.

    Connects to or auto-starts the Cloud Spanner emulator to deploy baseline_schema.sql
    and all migrations, introspects the true engine-collapsed schema DDL, and writes it.

    Args:
        target_path: Optional destination path. Defaults to get_schema_snapshot_path().
        project_id: GCP project ID used for model endpoint interpolation.
        region: GCP region used for model endpoint interpolation.
        progress_callback: Optional callback for reporting real-time progress messages.

    Returns:
        Path to the written schema snapshot file.

    Raises:
        ConnectionError: If the Spanner emulator is not reachable and auto-start fails.
        RuntimeError: If database initialization or schema compilation fails.
    """
    path = target_path or get_schema_snapshot_path()
    path.parent.mkdir(parents=True, exist_ok=True)

    content = generate_engine_schema_snapshot_sql(
        project_id=project_id,
        region=region,
        progress_callback=progress_callback,
    )

    path.write_text(content, encoding="utf-8")
    return path
