# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# models.py
import sqlalchemy as sa
from sqlalchemy.orm import relationship
from sqlalchemy.types import ARRAY, LargeBinary, String, Text

from datacommons_db.models.base import Base

NODE_TABLE_NAME = "Node"


class NodeModel(Base):
    __tablename__ = NODE_TABLE_NAME

    # Primary Key
    # autoincrement=False: subject_id is a preallocated DCID, not a sequence generated by the database.
    subject_id = sa.Column(sa.String(1024), primary_key=True, autoincrement=False)
    
    # Use String() for STRING(MAX); matches DDL nullability
    name = sa.Column(sa.String(), nullable=False, default='')
    value = sa.Column(sa.String(), nullable=False, default='')
    bytes = sa.Column(sa.LargeBinary(), nullable=True)
    types = sa.Column(ARRAY(sa.String(1024)), nullable=False, default=[])

    # This is a generated/hidden column. 
    # server_default/FetchedValue prevents SQLAlchemy from trying to 'INSERT' it.
    name_tokenlist = sa.Column(sa.LargeBinary(), server_default=FetchedValue(), system_hidden=True, nullable=True)

    # Relationships
    outgoing_edges = relationship(
        "EdgeModel",
        foreign_keys="EdgeModel.subject_id",
        back_populates="source_node",
        lazy="selectin", 
        cascade="all, delete-orphan",
    )

    incoming_edges = relationship(
        "EdgeModel",
        foreign_keys="EdgeModel.object_id", # Crucial: links to the object_id FK
        back_populates="target_node",        # Points to the matching relationship in EdgeModel
        lazy="selectin",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return f"<NodeModel(subject_id='{self.subject_id}', name='{self.name}')>"