name: Auto-Draft Release

on:
  push:
    branches:
      - main

jobs:
  check-bump:
    runs-on: ubuntu-latest
    outputs:
      is_bump: ${{ steps.check-bump.outputs.is_bump }}
      version: ${{ steps.check-bump.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check if version bump commit
        id: check-bump
        run: |
          commit_msg=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_msg"
          if [[ "$commit_msg" =~ ^chore:\ bump\ version\ to\ ([0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?) ]]; then
            version="${BASH_REMATCH[1]}"
            echo "is_bump=true" >> $GITHUB_OUTPUT
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "Detected version bump to: $version"
          else
            echo "is_bump=false" >> $GITHUB_OUTPUT
            echo "Not a version bump commit."
          fi

  gcp-integration-test:
    needs: check-bump
    if: needs.check-bump.outputs.is_bump == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SA_EMAIL }}

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: datcom-ci

      - name: Install uv and Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run GCP Integration Test
        env:
          DC_API_KEY: ${{ secrets.DC_API_KEY }}
        run: |
          TAG="${{ needs.check-bump.outputs.version }}"
          
          uv run python3 tests/datacommons-integration-tests/gcp_test_runner.py \
            --project-id datcom-ci \
            --dcp-version "$TAG" \
            --dc-api-key "$DC_API_KEY"

  hermetic-integration-test:
    needs: check-bump
    if: needs.check-bump.outputs.is_bump == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv and Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run hermetic integration test
        run: uv run pytest -s tests/datacommons-integration-tests/run_local_integration_test.py



